const MAX_ATTEMPTS = 4;
let isSubmitting = false;

const levels = [
  { id: "naruto", answerHashes: ["846f6a76ffc111552f1c9ca3a06d989d0c9c9b79c4fc25ff67f6207be512955c","566b933e9cbfdb3b5074827f398e5a7b593326e23e993e8f9bf4e83405f16225"], panels:[{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Naruto/image1.png",hint:"No hint"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Naruto/image2Naruto.png",hint:"Target: Shonen"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Naruto/Naruto3.png",hint:"Ended, N° of Tome: 72, Chapters: 700"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Naruto/Naruto5.png",hint:"I'm gonna become Hokage!"}]},
  { id: "onepiece", answerHashes: ["476e42f1152a32f2e5333664647c5fb8cdf8240d90dd803b02fb8bcdd9802356","683e44fb9176bab42256f9995ec12c2480553c02f87256da1f25f85ba982b815"], panels:[{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/OnePiece/Op1.png",hint:"No hint"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/OnePiece/Op2.png",hint:"Target: Shonen"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/OnePiece/Op3.png",hint:"Not Ended, N° of Tome: 114+, Chapters: 1176+"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/OnePiece/Op4.png",hint:"I'm Luffy! The Man Who Will Become the Pirate King!"}]},
  { id: "buglecall", answerHashes: ["bbd1c39ef394ac23c90833379b2b35ffe8baaa6b9bb7d322395ebcd7d307f503","8e2457d96e6095f2612b350b1291cc2f1219ff0201a715728898d7b63bab8595"], panels:[{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/BugleCall/1.png",hint:"No hint"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/BugleCall/2.png",hint:"Target: Shonen"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/BugleCall/3.png",hint:"Not Ended, Started in 2022, N° of tome: 13+"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/BugleCall/4.png",hint:"The main character hates the world and plays the trumpet, his name is Luca"}]},
  { id: "dandadan", answerHashes: ["ddd7c1e60f0010cd4cdc8815ad7879f6d6c331ef62f5f92c945c4e71cac2e43f"], panels:[{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Dandadan/Livello1.png",hint:"No hint"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Dandadan/Livello2.png",hint:"Target: Shonen"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Dandadan/Livello3.png",hint:"Not Ended, Started in 2021, N° of tome: 22+"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/Dandadan/Livello4.png",hint:"Okarun's Golden Balls"}]},
  { id: "musicofmarie", answerHashes: ["f4a2eda25ef8011dcc01f14c460610248f65ce9b1d98bc997d97b0add23d91ea","4fd324b1a0b42c77918cb0cb1c1ea3a8dcd130b21f8ccc70abfb6f1d42f1f177","b0a3adc1c7e4a30c9290fb47eb575379f8e535095c5dcc1f21884f74ff801bc3"], panels:[{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/MusicMarie/1.png",hint:"No hint"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/MusicMarie/2.png",hint:"Target: Seinen"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/MusicMarie/3.png",hint:"Ended, N° of Tome: 2, Chapters: 17"},{src:"https://github.com/Pasio99/guess-the-manga/raw/main/immagini/MusicMarie/4.png",hint:"Mangaka: Usamaru Furuya"}]}
];
let currentLevelId=0,currentPanel=0,attemptsMade=0,maxPanelReached=0,hintVisible=false,gameMode="play",levelFinished=false;
const $=id=>document.getElementById(id);
const normalizeAnswer=s=>String(s||"").trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/['’`]/g,"").replace(/[^\p{L}\p{N}]+/gu,"");
async function sha256Hex(input){const buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function isCorrectGuess(levelId,guess){const n=normalizeAnswer(guess);if(!n) return false; const h=await sha256Hex(n); return levels[levelId].answerHashes.includes(h);} 
async function persist(){if(gameMode!=="play"||levelFinished)return;await GTMStorage.savePlayState(currentLevelId,{attemptsMade,maxPanelReached,currentPanel,hintVisible});}
function setResult(msg,c){const r=$("result");r.textContent=msg;r.style.color=c||"#fff";}
async function setLevel(levelId){const playable=await GTMStorage.getFirstPlayableLevel(levels.length);const forced=Number(localStorage.getItem("navigateToLevel"));localStorage.removeItem("navigateToLevel");let target=Number.isInteger(forced)?forced:levelId; if(playable!==-1&&target>playable&&!(await GTMStorage.getLevelState(target)).status==="in_progress")target=playable;currentLevelId=Math.max(0,Math.min(levels.length-1,target));const st=await GTMStorage.getLevelState(currentLevelId);gameMode=(st.status==="solved"||st.status==="failed")?"view":"play";attemptsMade=st.attemptsMade;maxPanelReached=st.maxPanelReached;currentPanel=st.currentPanel;hintVisible=st.hintVisible;levelFinished=gameMode==="view";if(st.status==="not_started")await GTMStorage.startLevel(currentLevelId);render();}
function render(){const lvl=levels[currentLevelId];$("manga-panel").src=lvl.panels[currentPanel].src;$("level-indicator").textContent=`Manga #${currentLevelId+1}`;$("attempts-indicator").textContent=`Attempts: ${attemptsMade}/${MAX_ATTEMPTS}`;$("state-indicator").textContent=levelFinished?"View only":"In progress";const h=$("hint-overlay");h.textContent=hintVisible?lvl.panels[currentPanel].hint:"";h.classList.toggle("hidden",!hintVisible);$("submit-button").disabled=gameMode==="view"||!( $("user-guess").value.trim())||isSubmitting;$("user-guess").disabled=gameMode==="view";}
async function checkAnswer(){if(isSubmitting||gameMode==="view"||levelFinished)return;const input=$("user-guess");const g=input.value.trim();if(!g){render();return;}isSubmitting=true;render();attemptsMade++;await persist();const ok=await isCorrectGuess(currentLevelId,g);if(ok){setResult("Correct!","#42d77d");await GTMStorage.finishLevel(currentLevelId,"Correct");levelFinished=true;setTimeout(async()=>{const n=await GTMStorage.getFirstPlayableLevel(levels.length);window.location.href=n===-1?"FrontEnd/history.html":"index.html";},900);}else if(attemptsMade>=MAX_ATTEMPTS){setResult("Failed!","#ff6b6b");await GTMStorage.finishLevel(currentLevelId,"Failed");levelFinished=true;setTimeout(async()=>{const n=await GTMStorage.getFirstPlayableLevel(levels.length);window.location.href=n===-1?"FrontEnd/history.html":"index.html";},900);}else{setResult("Wrong answer!","#ff6b6b");currentPanel=Math.min(currentPanel+1,levels[currentLevelId].panels.length-1);maxPanelReached=Math.max(maxPanelReached,currentPanel);input.value="";await persist();}isSubmitting=false;render();}
function movePanel(d){const lim=levelFinished?levels[currentLevelId].panels.length-1:maxPanelReached;const np=Math.min(lim,Math.max(0,currentPanel+d));if(np!==currentPanel){currentPanel=np;persist();render();}}
function toggleHint(){hintVisible=!hintVisible;persist();render();}
window.addEventListener("DOMContentLoaded",async()=>{await setLevel(0);$("previous-button").addEventListener("click",()=>movePanel(-1));$("next-button").addEventListener("click",()=>movePanel(1));$("hint-button").addEventListener("click",toggleHint);$("submit-button").addEventListener("click",checkAnswer);$("user-guess").addEventListener("input",render);$("user-guess").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();if(!$("submit-button").disabled)checkAnswer();}});$("history-link").addEventListener("click",()=>persist());window.addEventListener("pagehide",persist);window.addEventListener("beforeunload",persist);document.addEventListener("visibilitychange",()=>{if(document.hidden)persist();});});
